import dotenv from "dotenv";

dotenv.config();

const OPEN_AI_KEY = process.env.OPEN_AI_KEY;
const TWILIO_ACCOUNT_SID = process.env.TWILIO_ACCOUNT_SID;
const TWILIO_AUTH_TOKEN = process.env.TWILIO_AUTH_TOKEN;
const DEEPGRAM_API_KEY = process.env.DEEPGRAM_API_KEY;
const PORT = process.env.PORT || 3000;
const REDIS_CLIENT_URL = process.env.REDIS_CLIENT_URL;
const TWILIO_TO_NUMBER = process.env.TWILIO_TO_NUMBER;
const TWILIO_FROM_NUMBER = process.env.TWILIO_FROM_NUMBER;
const API_BASE_URL = process.env.API_BASE_URL;
const LLM_MODEL_SWITCH_DURATION = process.env.LLM_MODEL_SWITCH_DURATION;
const HOST = process.env.HOST;
const CALL_QUEUE_DELAY = process.env.CALL_QUEUE_DELAY;

export {
  API_BASE_URL,
  CALL_QUEUE_DELAY,
  DEEPGRAM_API_KEY,
  HOST,
  LLM_MODEL_SWITCH_DURATION,
  OPEN_AI_KEY,
  PORT,
  REDIS_CLIENT_URL,
  TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN,
  TWILIO_FROM_NUMBER,
  TWILIO_TO_NUMBER,
};
